server:
  port: 8082
  servlet:
    session:
      cookie:
        name: UISESSIONCOUPON

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          authing:
            client-name: authing
#            client-id: 5f8d2861599d91045743fad3
#            client-secret: 439d9e49cc78c318419d72996d81bc61
            client-id: 6061e247f16c6c39fcc4b35d
            client-secret: 505049220ea0ed908924bec8e0d2a6d1
            authorization-grant-type: client_credentials
            scope:
              - openid
              - profile
        provider:
          authing:
            token-uri: https://zztest1.authing.cn/oidc/token

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    import org.springframework.cloud.netflix.zuul: DEBUG
