spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          authing:
            client-id: {替换为您的App ID如：App Secret5e72d72e3798fb03e1d57b13}
            client-secret: {替换为您的App Secret如：931f19ce2161e5560c072f586c706ee6}
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: post
            scope:
              - openid
              - profile
        provider:
          authing:
            issuer-uri: https://{替换为您的Issuer，如：authing-net-sdk-demo}.authing.cn/oauth/oidc
            user-name-attribute: preferred_username
#            user-name-attribute: name
#            user-name-attribute: username

