server:
  port: 8082
  servlet:
    session:
      cookie:
        name: UISESSIONCOUPON

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: b7fb29a538bb19b09365
            client-secret: 2fbfd22e69e61d873bad55143538770748a76d3a
          authing:
            client-name: authing
            client-id: 5f8d2861599d91045743fad3
            client-secret: 439d9e49cc78c318419d72996d81bc61
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: post
            scope:
              - openid
              - profile
        provider:
          authing:
            issuer-uri: https://zztest1.authing.cn/oidc
            user-name-attribute: name

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    import org.springframework.cloud.netflix.zuul: DEBUG

#
#---
#server:
#  ssl:
#    key-store-type: PKCS12
#    key-store-password: 123456
#    key-store: classpath:star.taiji.com.cn.pfx