server:
  port: 8081
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER


spring:
  security:
    oauth2:
      client:
        registration:
          tdf:
            client-id: 6061a1399153fa35510b4249
            client-secret: db1054f99722c795d80599e3c3a322de




