server:
  port: 8081
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER


spring:
  security:
    oauth2:
      client:
        registration:
          authing:
            client-id: 6061e247f16c6c39fcc4b35d
            client-secret: 505049220ea0ed908924bec8e0d2a6d1



