server:
  port: 8050
  servlet:
    session:
      cookie:
        # 避免与本地启动authorizationserver默认的cookie名称：JSESSIONID冲突
        name: UISESSIONCOUPON

---
# OAuth2 Client/Login配置
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: b7fb29a538bb19b09365
            client-secret: 2fbfd22e69e61d873bad55143538770748a76d3a
          authing:
            client-name: authing
            client-id: 5f8d2861599d91045743fad3
            client-secret: 439d9e49cc78c318419d72996d81bc61
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: post
            scope:
              - openid
              - profile
        provider:
          authing:
            issuer-uri: https://zztest1.authing.cn/oidc
            user-name-attribute: name

logging:
  level:
    org.springframework.web: Debug
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure: INFO
